### ISSUE TITLE
Could the bot merge master?

### ISSUE THREAD

**Issue by bkchr** [paritytech/auto-merge-bot#21]
When the branch is out of date, it looks like auto merge is waiting. It would be nice if in such a situation the bot just merges master.

**Comment by bkchr** [comment]
CC @Bullrich 

See https://github.com/polkadot-fellows/runtimes/pull/114#issuecomment-1877105208 as an example.

**Comment by Bullrich** [comment]
Hi @bkchr!

I have been running some experiments on this and, unfortunately, it can not be done 😞 

This is because a GitHub action can only _modify a branch that belongs to the repository_, and PRs to [polkadot-fellows/runtimes](https://github.com/polkadot-fellows/runtimes) are _done from a fork, which does not belong to the repository_.

> Could not update pull request due to an authorisation error. This is probably because this pull request is from a fork and the current token does not have write access to the forked repository. Error was: Resource not accessible by integration

I tried with the existing action [autoupdate](https://github.com/marketplace/actions/auto-update) which provides exactly the features that you need but also had the same problem.

---

A possible solution for this could be [merge-queues](https://docs.github.com/en/repositories/configuring-branches-and-merges-in-your-repository/configuring-pull-request-merges/managing-a-merge-queue) which @alvicsam has implemented in [paritytech/polkadot-sdk](https://github.com/paritytech/polkadot-sdk). It requires a trickier setup, but it was developed for this particular purpose.

Let me know what you think.

**Comment by bkchr** [comment]
And what is with this? https://github.com/adRise/update-pr-branch

**Comment by Bullrich** [comment]
> And what is with this? https://github.com/adRise/update-pr-branch

This one uses [a different method](https://github.com/adRise/update-pr-branch/blob/master/src/lib/github.js#L45). Seems to be kind of new (we didn't knew about it and had only tried with the old fashioned method).

[Update a Pull Request Branch](https://docs.github.com/en/rest/pulls/pulls?apiVersion=2022-11-28#update-a-pull-request-branch).

Thanks, it seems that this could be the solution for our problem!

I experimented with it and noticed different behaviours based on this checkbox:
<img width="315" alt="image" src="https://github.com/paritytech/auto-merge-bot/assets/8524599/48076fa3-4b06-4659-942b-5634d9a9dfe7">

If it is off, it throws an error:
> Error: Fail to update PR with error: HttpError: user doesn't have permission to update head repository

If it is on, it works by default.

The only problem that I see is that it doesn't have error handling of [a failed case](https://github.com/adRise/update-pr-branch/blob/master/src/index.js#L24), so if one of the PRs have this check disabled, it will throw the whole process.

The task itself is quite small. I think I can make a small action using this method that will fulfill this requirements in no time.

**Comment by Bullrich** [comment]
A PR with the action has been created in polkadot-fellows/runtimes#139.

It uses the newly created action [`up-to-date`](https://github.com/paritytech/up-to-date-action)

**Comment by Bullrich** [comment]
Task fulfilled with [action](https://github.com/polkadot-fellows/runtimes/actions/runs/7476231563)

Closed by finishing paritytech/up-to-date-action#1 and merging:
- polkadot-fellows/runtimes#139
- polkadot-fellows/runtimes#141
